###
GET http://localhost:8080/stock
Content-Type: application/json

{
  "netIncome": {
    "test": true,
    "unknownValuePass": true,
    "periods": [
      "THIS_YEAR_EXPECTED",
      "LAST_YEAR",
      "TWO_YEARS_AGO",
      "THREE_YEARS_AGO"
    ],
    "threshold": 0
  },
  "operatingIncome": {
    "test": true,
    "unknownValuePass": true,
    "periods": [
      "LAST_YEAR",
      "TWO_YEARS_AGO",
      "THREE_YEARS_AGO"
    ],
    "threshold": 0
  },
  "debtRatio": {
    "test": false,
    "unknownValuePass": true,
    "periods": [
      "LAST_YEAR",
      "TWO_YEARS_AGO",
      "THREE_YEARS_AGO"
    ],
    "threshold": 100
  },
  "quickRatio": {
    "test": false,
    "unknownValuePass": true,
    "periods": [
      "LAST_YEAR",
      "TWO_YEARS_AGO",
      "THREE_YEARS_AGO"
    ],
    "threshold": 70
  },
  "reserveRatio": {
    "test": false,
    "unknownValuePass": false,
    "periods": [
      "LAST_YEAR"
    ],
    "threshold": 7000
  },
  "per": {
    "test": false,
    "unknownValuePass": false,
    "periods": [
      "LAST_YEAR"
    ],
    "threshold": 50
  },
  "pbr": {
    "test": false,
    "unknownValuePass": false,
    "periods": [
      "LAST_YEAR"
    ],
    "threshold": 3
  },
  "expectedPer": {
    "test": false,
    "unknownValuePass": false,
    "threshold": 100
  },
  "epsIncreaseRate": {
    "test": true,
    "unknownValuePass": false,
    "turnedPositivePass": false,
    "basePeriod": "THIS_YEAR_EXPECTED",
    "targetPeriod": "NEXT_YEAR_EXPECTED",
    "rate": 5
  },
  "dividendYield": {
    "test": false,
    "unknownValuePass": true,
    "periods": [
      "LAST_YEAR",
      "TWO_YEARS_AGO"
    ],
    "threshold": 1.8
  },
  "expectedDividendYield": {
    "test": true,
    "unknownValuePass": false,
    "periods": [
      "NEXT_YEAR_EXPECTED"
    ],
    "threshold": 2
  },
  "annualPriceVolatility": {
    "test": false,
    "threshold": 1.7
  },
  "annualHigherCurrentPriceRatio": {
    "test": false,
    "minThreshold": 1.99,
    "maxThreshold": 10
  }
}